version: 2

builds:
  - main: .
    binary: ffd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^perf"
      - "^refactor"
